version: 2

project_name: dendrite

before:
  hooks:
    - go mod tidy

builds:
  - id: dendrite
    main: ./cmd/dendrite
    binary: dendrite
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - id: dendrite
    formats: ['tar.gz']
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    ids:
      - dendrite

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

changelog:
  sort: asc

release:
  use_existing_draft: true
